name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release-linux:
    name: Publish artifacts to github packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: gradle/wrapper-validation-action@v1

      - name: Setup AdoptOpenJDK 11
        uses: joschi/setup-jdk@v2
        with:
          java-version: '11' # The OpenJDK version to make available on the path

      - uses: burrunan/gradle-cache-action@v1
        name: Publish graphql-dsl (cached)
        with:
          job-id: jdk11
          arguments: publishAllPublicationsToGitHubPackagesRepository
          gradle-version: wrapper
          properties: |
            gpr.user=${{ secrets.GPR_USER }}
            gpr.key=${{ secrets.GPR_KEY }}
